using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace NewYearLanding.Model {
    public class Company {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // external Id, easier to reference: 1,2,3 or A, B, C etc.
        public int CompanyId { get; set; }

        public string CompanyTitle { get; set; }

        public Guid PublicGuid { get; set; }

        public Guid FullAccessGuid { get; set; }

        [BsonDateTimeOptions]
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
    }
}